version: "2"

services:

  web:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    volumes:
      - "mysqldrupal8data:/var/lib/mysql"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 3306:3306
    
volumes:
  mysqldrupal8data:
    driver: local

